#lang racket
(provide (all-defined-out))
(define (Prelude title css . body*)
  `(html
    (head
     (meta ((charset "utf-8")))
     (title ,title)
     (link ((rel "stylesheet") (href ,css))))
    (body . ,body*)))
(define (H1 xml)
  `(h1 ,xml))
(define (H2 xml)
  `(h2 ,xml))
(define (H3 xml)
  `(h3 ,xml))
(define (H4 xml)
  `(h4 ,xml))
(define (H5 xml)
  `(h5 ,xml))
(define (H6 xml)
  `(h6 ,xml))
(define (P . xml*)
  `(p . ,xml*))
(define (Pre xml)
  `(pre ,xml))
(define (Code xml)
  `(code ,xml))
(define (Pre-code xml)
  `(pre (code ,xml)))
(define (Div . xml*)
  `(div . ,xml*))
(define (Ul . xml*)
  (cons 'ul (map (lambda (xml) `(li ,xml)) xml*)))
(define (Ol . xml*)
  (cons 'ol (map (lambda (xml) `(li ,xml)) xml*)))
(define (A xml href)
  `(a ((href ,href)) ,xml))